// <auto-generated />
using System;
using FamilyPlus.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FamilyPlus.Api.Migrations
{
    [DbContext(typeof(FinanceDbContext))]
    [Migration("20260914013650_Sprint8CoreLedger")]
    partial class Sprint8CoreLedger
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("FamilyPlus.Api.Entities.Alerta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChaveUnica")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DataGeracao")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DataLeitura")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EntidadeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntidadeOrigem")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FamiliaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Resolvido")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Severidade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DataGeracao")
                        .HasDatabaseName("IDX_ALERTA_DATA");

                    b.HasIndex("Resolvido")
                        .HasDatabaseName("IDX_ALERTA_RESOLVIDO");

                    b.HasIndex("Severidade")
                        .HasDatabaseName("IDX_ALERTA_SEVERIDADE");

                    b.HasIndex("Tipo")
                        .HasDatabaseName("IDX_ALERTA_TIPO");

                    b.HasIndex("ChaveUnica", "Resolvido");

                    b.ToTable("alerta", (string)null);
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.Assinatura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CartaoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContaId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DataCancelamento")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DataInicio")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FamiliaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MembroId")
                        .HasColumnType("TEXT");

                    b.Property<int>("MetodoPagamento")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacao")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Periodicidade")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ProximaCobranca")
                        .HasColumnType("TEXT");

                    b.Property<long>("ValorCentavos")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Ativo")
                        .HasDatabaseName("IDX_ASSINATURA_ATIVA");

                    b.HasIndex("CartaoId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("ContaId");

                    b.HasIndex("MembroId");

                    b.HasIndex("ProximaCobranca")
                        .HasDatabaseName("IDX_ASSINATURA_PROXIMA_COBRANCA");

                    b.ToTable("assinatura", (string)null);
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.Auditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DadosAnteriores")
                        .HasColumnType("TEXT");

                    b.Property<string>("DadosNovos")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("Entidade")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntidadeId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Operacao")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Data");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("Entidade", "EntidadeId");

                    b.ToTable("auditoria", (string)null);
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.Cartao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bandeira")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContaPagamentoPadraoId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<int>("DiaFechamento")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiaVencimento")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("FamiliaId")
                        .HasColumnType("TEXT");

                    b.Property<long>("LimiteTotalCentavos")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MembroId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("UltimosDigitos")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContaPagamentoPadraoId");

                    b.HasIndex("MembroId");

                    b.ToTable("cartao", (string)null);
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CategoriaPaiId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FamiliaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaPaiId");

                    b.ToTable("categoria", (string)null);
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.CompraCartao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CartaoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DataCompra")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FamiliaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MembroId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacao")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantidadeParcelas")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ValorTotalCentavos")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CartaoId")
                        .HasDatabaseName("IDX_COMPRA_CARTAO");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("DataCompra")
                        .HasDatabaseName("IDX_COMPRA_DATA");

                    b.HasIndex("MembroId");

                    b.ToTable("compra_cartao", (string)null);
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.ConexaoFinanceira", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Configuracao")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FamiliaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Instituicao")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("conexao_financeira", (string)null);
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.Configuracao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Chave")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Chave")
                        .IsUnique();

                    b.ToTable("configuracao", (string)null);
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.ConfiguracaoFamilia", b =>
                {
                    b.Property<Guid>("FamiliaId")
                        .HasColumnType("TEXT");

                    b.Property<int>("InicioMesFinanceiro")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Moeda")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<int>("PrimeiroDiaSemana")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("FamiliaId");

                    b.ToTable("configuracao_familia", (string)null);
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.ConfiguracaoNotificacao", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("TEXT");

                    b.Property<int>("AntecedenciaDias")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AvisarContasProximas")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AvisarFatura")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AvisarOrcamento")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AvisarSaldoProjetadoNegativo")
                        .HasColumnType("INTEGER");

                    b.HasKey("UsuarioId");

                    b.ToTable("configuracao_notificacao", (string)null);
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.Conta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DataSaldoInicial")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FamiliaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Instituicao")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MembroId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Moeda")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("SaldoInicialCentavos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MembroId");

                    b.ToTable("conta", (string)null);
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.EstornoCartao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompraCartaoId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FamiliaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FaturaId")
                        .HasColumnType("TEXT");

                    b.Property<long>("ValorCentavos")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompraCartaoId");

                    b.HasIndex("FaturaId");

                    b.ToTable("estorno_cartao", (string)null);
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.Familia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativa")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FamiliaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MoedaPadrao")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("familia", (string)null);
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.Fatura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CartaoId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Competencia")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ContaPagamentoId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DataFechamento")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DataPagamento")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DataVencimento")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FamiliaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LancamentoPagamentoId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ValorTotalCentavos")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CartaoId")
                        .HasDatabaseName("IDX_FATURA_CARTAO");

                    b.HasIndex("Competencia")
                        .HasDatabaseName("IDX_FATURA_COMPETENCIA");

                    b.HasIndex("ContaPagamentoId");

                    b.HasIndex("LancamentoPagamentoId")
                        .IsUnique();

                    b.HasIndex("Status")
                        .HasDatabaseName("IDX_FATURA_STATUS");

                    b.HasIndex("CartaoId", "Competencia")
                        .IsUnique();

                    b.ToTable("fatura", (string)null);
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.Importacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ConcluidaEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FamiliaId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ItensComErro")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItensValidos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalItens")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("importacao", (string)null);
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.ImportacaoArquivo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FamiliaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hash")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ImportacaoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.Property<long>("TamanhoBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ImportacaoId");

                    b.ToTable("importacao_arquivo", (string)null);
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.ImportacaoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dados")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Erro")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FamiliaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("HashDedupe")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ImportacaoId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Linha")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Valido")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ImportacaoId");

                    b.ToTable("importacao_item", (string)null);
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.ItemOrcamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FamiliaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MembroId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacao")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrcamentoId")
                        .HasColumnType("TEXT");

                    b.Property<long>("ValorPlanejadoCentavos")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId")
                        .HasDatabaseName("IDX_ITEM_ORCAMENTO_CATEGORIA");

                    b.HasIndex("MembroId")
                        .HasDatabaseName("IDX_ITEM_ORCAMENTO_MEMBRO");

                    b.HasIndex("OrcamentoId")
                        .HasDatabaseName("IDX_ITEM_ORCAMENTO_ORCAMENTO");

                    b.HasIndex("OrcamentoId", "CategoriaId", "MembroId")
                        .IsUnique();

                    b.ToTable("item_orcamento", (string)null);
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.Lancamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CategoriaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContaId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CriadoPorUsuarioId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DataCompetencia")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DataEfetivacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DataVencimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FamiliaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MembroId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Natureza")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacao")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OrigemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrigemTipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<long>("ValorCentavos")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ValorPrevistoCentavos")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("ContaId")
                        .HasDatabaseName("IDX_LANCAMENTO_CONTA");

                    b.HasIndex("CriadoPorUsuarioId");

                    b.HasIndex("DataCompetencia")
                        .HasDatabaseName("IDX_LANCAMENTO_COMPETENCIA");

                    b.HasIndex("DataEfetivacao")
                        .HasDatabaseName("IDX_LANCAMENTO_EFETIVACAO");

                    b.HasIndex("MembroId")
                        .HasDatabaseName("IDX_LANCAMENTO_MEMBRO");

                    b.HasIndex("Status")
                        .HasDatabaseName("IDX_LANCAMENTO_STATUS");

                    b.HasIndex("OrigemTipo", "OrigemId")
                        .HasDatabaseName("IDX_LANCAMENTO_ORIGEM");

                    b.ToTable("lancamento", (string)null);
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.Membro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DataNascimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FamiliaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FamiliaId");

                    b.ToTable("membro", (string)null);
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.OcorrenciaRecorrencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CompraCartaoId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DataPrevista")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FamiliaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LancamentoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacao")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RecorrenciaId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("TransacaoId")
                        .HasColumnType("TEXT");

                    b.Property<long>("ValorPrevistoCentavos")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ValorRealizadoCentavos")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompraCartaoId");

                    b.HasIndex("DataPrevista")
                        .HasDatabaseName("IDX_OCORRENCIA_DATA");

                    b.HasIndex("LancamentoId")
                        .IsUnique();

                    b.HasIndex("RecorrenciaId")
                        .HasDatabaseName("IDX_OCORRENCIA_RECORRENCIA");

                    b.HasIndex("Status")
                        .HasDatabaseName("IDX_OCORRENCIA_STATUS");

                    b.HasIndex("TransacaoId");

                    b.HasIndex("RecorrenciaId", "DataPrevista")
                        .IsUnique();

                    b.ToTable("ocorrencia_recorrencia", (string)null);
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.Orcamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Ano")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FamiliaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MembroId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Mes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModoReceitaPrevista")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Observacao")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<long>("ReceitaPrevistaCentavos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MembroId")
                        .HasDatabaseName("IDX_ORCAMENTO_MEMBRO");

                    b.HasIndex("Status")
                        .HasDatabaseName("IDX_ORCAMENTO_STATUS");

                    b.HasIndex("Ano", "Mes")
                        .HasDatabaseName("IDX_ORCAMENTO_ANO_MES");

                    b.ToTable("orcamento", (string)null);
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.ParcelaCartao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompraCartaoId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DataCompetencia")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FamiliaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FaturaId")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroParcela")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantidadeTotal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ValorCentavos")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompraCartaoId")
                        .HasDatabaseName("IDX_PARCELA_COMPRA");

                    b.HasIndex("DataCompetencia")
                        .HasDatabaseName("IDX_PARCELA_COMPETENCIA");

                    b.HasIndex("FaturaId")
                        .HasDatabaseName("IDX_PARCELA_FATURA");

                    b.ToTable("parcela_cartao", (string)null);
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.PerfilAcesso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FamiliaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Sistema")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FamiliaId", "Nome")
                        .IsUnique();

                    b.ToTable("perfil_acesso", (string)null);
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.PerfilPermissao", b =>
                {
                    b.Property<Guid>("PerfilAcessoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PermissaoId")
                        .HasColumnType("TEXT");

                    b.HasKey("PerfilAcessoId", "PermissaoId");

                    b.HasIndex("PermissaoId");

                    b.ToTable("perfil_permissao", (string)null);
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.Permissao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FamiliaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FamiliaId", "Codigo")
                        .IsUnique();

                    b.ToTable("permissao", (string)null);
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.PermissaoEscopo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FamiliaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Recurso")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoEscopo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "Recurso")
                        .IsUnique();

                    b.ToTable("permissao_escopo", (string)null);
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.PermissaoMembro", b =>
                {
                    b.Property<Guid>("PermissaoEscopoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MembroId")
                        .HasColumnType("TEXT");

                    b.HasKey("PermissaoEscopoId", "MembroId");

                    b.HasIndex("MembroId");

                    b.ToTable("permissao_membro", (string)null);
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.PreferenciaUsuario", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ConfirmarOperacoes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FormatoData")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Idioma")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("ItensPorPagina")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PaginaInicial")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("PeriodoPadraoDashboard")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tema")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("UsuarioId");

                    b.ToTable("preferencia_usuario", (string)null);
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.RateioDespesa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FamiliaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LancamentoId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PadraoAplicado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TransacaoId")
                        .HasColumnType("TEXT");

                    b.Property<long>("ValorDespesaCentavos")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LancamentoId")
                        .IsUnique();

                    b.HasIndex("TransacaoId")
                        .IsUnique();

                    b.ToTable("rateio_despesa", (string)null);
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.RateioDespesaItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FamiliaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MembroId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Percentual")
                        .HasPrecision(12, 4)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RateioDespesaId")
                        .HasColumnType("TEXT");

                    b.Property<long>("ValorCentavos")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MembroId");

                    b.HasIndex("RateioDespesaId");

                    b.ToTable("rateio_despesa_item", (string)null);
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.Recorrencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Classificacao")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ContaId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DataFim")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DataInicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("DiaReferencia")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("FamiliaId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Frequencia")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("GerarAutomaticamente")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MembroId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacao")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ProximaOcorrencia")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ValorCentavos")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ValorVariavel")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("ContaId");

                    b.HasIndex("MembroId");

                    b.HasIndex("ProximaOcorrencia")
                        .HasDatabaseName("IDX_RECORRENCIA_PROXIMA");

                    b.HasIndex("Status")
                        .HasDatabaseName("IDX_RECORRENCIA_STATUS");

                    b.ToTable("recorrencia", (string)null);
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.SessaoLocal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CriadaEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("EncerradaEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiraEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("sessao_local", (string)null);
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.Transacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CategoriaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContaId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DataCompetencia")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DataMovimentacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FamiliaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LancamentoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MembroId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacao")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Origem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("TransferenciaId")
                        .HasColumnType("TEXT");

                    b.Property<long>("ValorCentavos")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId")
                        .HasDatabaseName("IDX_TRANSACAO_CATEGORIA");

                    b.HasIndex("ContaId")
                        .HasDatabaseName("IDX_TRANSACAO_CONTA");

                    b.HasIndex("DataMovimentacao")
                        .HasDatabaseName("IDX_TRANSACAO_DATA");

                    b.HasIndex("LancamentoId")
                        .IsUnique();

                    b.HasIndex("MembroId")
                        .HasDatabaseName("IDX_TRANSACAO_MEMBRO");

                    b.HasIndex("Status")
                        .HasDatabaseName("IDX_TRANSACAO_STATUS");

                    b.HasIndex("TransferenciaId");

                    b.ToTable("transacao", (string)null);
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.Transferencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContaDestinoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContaOrigemId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FamiliaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MembroId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ValorCentavos")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ContaDestinoId");

                    b.HasIndex("ContaOrigemId");

                    b.HasIndex("Data");

                    b.HasIndex("MembroId");

                    b.ToTable("transferencia", (string)null);
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FamiliaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MembroId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UltimoAcessoEm")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.HasIndex("MembroId");

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.UsuarioPerfil", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PerfilAcessoId")
                        .HasColumnType("TEXT");

                    b.HasKey("UsuarioId", "PerfilAcessoId");

                    b.HasIndex("PerfilAcessoId");

                    b.ToTable("usuario_perfil", (string)null);
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.Assinatura", b =>
                {
                    b.HasOne("FamilyPlus.Api.Entities.Cartao", "Cartao")
                        .WithMany()
                        .HasForeignKey("CartaoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FamilyPlus.Api.Entities.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyPlus.Api.Entities.Conta", "Conta")
                        .WithMany()
                        .HasForeignKey("ContaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyPlus.Api.Entities.Membro", "Membro")
                        .WithMany()
                        .HasForeignKey("MembroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cartao");

                    b.Navigation("Categoria");

                    b.Navigation("Conta");

                    b.Navigation("Membro");
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.Auditoria", b =>
                {
                    b.HasOne("FamilyPlus.Api.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.Cartao", b =>
                {
                    b.HasOne("FamilyPlus.Api.Entities.Conta", "ContaPagamentoPadrao")
                        .WithMany()
                        .HasForeignKey("ContaPagamentoPadraoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyPlus.Api.Entities.Membro", "Membro")
                        .WithMany()
                        .HasForeignKey("MembroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ContaPagamentoPadrao");

                    b.Navigation("Membro");
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.Categoria", b =>
                {
                    b.HasOne("FamilyPlus.Api.Entities.Categoria", "CategoriaPai")
                        .WithMany("Filhas")
                        .HasForeignKey("CategoriaPaiId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CategoriaPai");
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.CompraCartao", b =>
                {
                    b.HasOne("FamilyPlus.Api.Entities.Cartao", "Cartao")
                        .WithMany()
                        .HasForeignKey("CartaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyPlus.Api.Entities.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyPlus.Api.Entities.Membro", "Membro")
                        .WithMany()
                        .HasForeignKey("MembroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cartao");

                    b.Navigation("Categoria");

                    b.Navigation("Membro");
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.ConfiguracaoFamilia", b =>
                {
                    b.HasOne("FamilyPlus.Api.Entities.Familia", "Familia")
                        .WithOne()
                        .HasForeignKey("FamilyPlus.Api.Entities.ConfiguracaoFamilia", "FamiliaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Familia");
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.ConfiguracaoNotificacao", b =>
                {
                    b.HasOne("FamilyPlus.Api.Entities.Usuario", "Usuario")
                        .WithOne()
                        .HasForeignKey("FamilyPlus.Api.Entities.ConfiguracaoNotificacao", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.Conta", b =>
                {
                    b.HasOne("FamilyPlus.Api.Entities.Membro", "Membro")
                        .WithMany("Contas")
                        .HasForeignKey("MembroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Membro");
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.EstornoCartao", b =>
                {
                    b.HasOne("FamilyPlus.Api.Entities.CompraCartao", "CompraCartao")
                        .WithMany("Estornos")
                        .HasForeignKey("CompraCartaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyPlus.Api.Entities.Fatura", "Fatura")
                        .WithMany("Estornos")
                        .HasForeignKey("FaturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CompraCartao");

                    b.Navigation("Fatura");
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.Fatura", b =>
                {
                    b.HasOne("FamilyPlus.Api.Entities.Cartao", "Cartao")
                        .WithMany("Faturas")
                        .HasForeignKey("CartaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyPlus.Api.Entities.Conta", "ContaPagamento")
                        .WithMany()
                        .HasForeignKey("ContaPagamentoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FamilyPlus.Api.Entities.Lancamento", null)
                        .WithMany()
                        .HasForeignKey("LancamentoPagamentoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cartao");

                    b.Navigation("ContaPagamento");
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.ImportacaoArquivo", b =>
                {
                    b.HasOne("FamilyPlus.Api.Entities.Importacao", "Importacao")
                        .WithMany("Arquivos")
                        .HasForeignKey("ImportacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Importacao");
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.ImportacaoItem", b =>
                {
                    b.HasOne("FamilyPlus.Api.Entities.Importacao", "Importacao")
                        .WithMany("Itens")
                        .HasForeignKey("ImportacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Importacao");
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.ItemOrcamento", b =>
                {
                    b.HasOne("FamilyPlus.Api.Entities.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyPlus.Api.Entities.Membro", "Membro")
                        .WithMany()
                        .HasForeignKey("MembroId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FamilyPlus.Api.Entities.Orcamento", "Orcamento")
                        .WithMany("Itens")
                        .HasForeignKey("OrcamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Membro");

                    b.Navigation("Orcamento");
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.Lancamento", b =>
                {
                    b.HasOne("FamilyPlus.Api.Entities.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FamilyPlus.Api.Entities.Conta", "Conta")
                        .WithMany()
                        .HasForeignKey("ContaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyPlus.Api.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("CriadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FamilyPlus.Api.Entities.Membro", "Membro")
                        .WithMany()
                        .HasForeignKey("MembroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Conta");

                    b.Navigation("Membro");
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.Membro", b =>
                {
                    b.HasOne("FamilyPlus.Api.Entities.Familia", "Familia")
                        .WithMany("Membros")
                        .HasForeignKey("FamiliaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Familia");
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.OcorrenciaRecorrencia", b =>
                {
                    b.HasOne("FamilyPlus.Api.Entities.CompraCartao", "CompraCartao")
                        .WithMany()
                        .HasForeignKey("CompraCartaoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FamilyPlus.Api.Entities.Lancamento", null)
                        .WithMany()
                        .HasForeignKey("LancamentoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FamilyPlus.Api.Entities.Recorrencia", "Recorrencia")
                        .WithMany("Ocorrencias")
                        .HasForeignKey("RecorrenciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyPlus.Api.Entities.Transacao", "Transacao")
                        .WithMany()
                        .HasForeignKey("TransacaoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CompraCartao");

                    b.Navigation("Recorrencia");

                    b.Navigation("Transacao");
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.Orcamento", b =>
                {
                    b.HasOne("FamilyPlus.Api.Entities.Membro", "Membro")
                        .WithMany()
                        .HasForeignKey("MembroId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Membro");
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.ParcelaCartao", b =>
                {
                    b.HasOne("FamilyPlus.Api.Entities.CompraCartao", "CompraCartao")
                        .WithMany("Parcelas")
                        .HasForeignKey("CompraCartaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyPlus.Api.Entities.Fatura", "Fatura")
                        .WithMany("Parcelas")
                        .HasForeignKey("FaturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CompraCartao");

                    b.Navigation("Fatura");
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.PerfilPermissao", b =>
                {
                    b.HasOne("FamilyPlus.Api.Entities.PerfilAcesso", "PerfilAcesso")
                        .WithMany("Permissoes")
                        .HasForeignKey("PerfilAcessoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyPlus.Api.Entities.Permissao", "Permissao")
                        .WithMany("Perfis")
                        .HasForeignKey("PermissaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerfilAcesso");

                    b.Navigation("Permissao");
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.PermissaoEscopo", b =>
                {
                    b.HasOne("FamilyPlus.Api.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.PermissaoMembro", b =>
                {
                    b.HasOne("FamilyPlus.Api.Entities.Membro", "Membro")
                        .WithMany()
                        .HasForeignKey("MembroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyPlus.Api.Entities.PermissaoEscopo", "PermissaoEscopo")
                        .WithMany("Membros")
                        .HasForeignKey("PermissaoEscopoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Membro");

                    b.Navigation("PermissaoEscopo");
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.PreferenciaUsuario", b =>
                {
                    b.HasOne("FamilyPlus.Api.Entities.Usuario", "Usuario")
                        .WithOne()
                        .HasForeignKey("FamilyPlus.Api.Entities.PreferenciaUsuario", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.RateioDespesa", b =>
                {
                    b.HasOne("FamilyPlus.Api.Entities.Lancamento", null)
                        .WithMany()
                        .HasForeignKey("LancamentoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FamilyPlus.Api.Entities.Transacao", "Transacao")
                        .WithMany()
                        .HasForeignKey("TransacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transacao");
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.RateioDespesaItem", b =>
                {
                    b.HasOne("FamilyPlus.Api.Entities.Membro", "Membro")
                        .WithMany()
                        .HasForeignKey("MembroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyPlus.Api.Entities.RateioDespesa", "RateioDespesa")
                        .WithMany("Itens")
                        .HasForeignKey("RateioDespesaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Membro");

                    b.Navigation("RateioDespesa");
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.Recorrencia", b =>
                {
                    b.HasOne("FamilyPlus.Api.Entities.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyPlus.Api.Entities.Conta", "Conta")
                        .WithMany()
                        .HasForeignKey("ContaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyPlus.Api.Entities.Membro", "Membro")
                        .WithMany()
                        .HasForeignKey("MembroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Conta");

                    b.Navigation("Membro");
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.SessaoLocal", b =>
                {
                    b.HasOne("FamilyPlus.Api.Entities.Usuario", "Usuario")
                        .WithMany("Sessoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.Transacao", b =>
                {
                    b.HasOne("FamilyPlus.Api.Entities.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FamilyPlus.Api.Entities.Conta", "Conta")
                        .WithMany()
                        .HasForeignKey("ContaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyPlus.Api.Entities.Lancamento", null)
                        .WithMany()
                        .HasForeignKey("LancamentoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FamilyPlus.Api.Entities.Membro", "Membro")
                        .WithMany()
                        .HasForeignKey("MembroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyPlus.Api.Entities.Transferencia", "Transferencia")
                        .WithMany("Transacoes")
                        .HasForeignKey("TransferenciaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Categoria");

                    b.Navigation("Conta");

                    b.Navigation("Membro");

                    b.Navigation("Transferencia");
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.Transferencia", b =>
                {
                    b.HasOne("FamilyPlus.Api.Entities.Conta", null)
                        .WithMany()
                        .HasForeignKey("ContaDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyPlus.Api.Entities.Conta", null)
                        .WithMany()
                        .HasForeignKey("ContaOrigemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyPlus.Api.Entities.Membro", null)
                        .WithMany()
                        .HasForeignKey("MembroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.Usuario", b =>
                {
                    b.HasOne("FamilyPlus.Api.Entities.Membro", "Membro")
                        .WithMany()
                        .HasForeignKey("MembroId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Membro");
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.UsuarioPerfil", b =>
                {
                    b.HasOne("FamilyPlus.Api.Entities.PerfilAcesso", "PerfilAcesso")
                        .WithMany("Usuarios")
                        .HasForeignKey("PerfilAcessoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyPlus.Api.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerfilAcesso");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.Cartao", b =>
                {
                    b.Navigation("Faturas");
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.Categoria", b =>
                {
                    b.Navigation("Filhas");
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.CompraCartao", b =>
                {
                    b.Navigation("Estornos");

                    b.Navigation("Parcelas");
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.Familia", b =>
                {
                    b.Navigation("Membros");
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.Fatura", b =>
                {
                    b.Navigation("Estornos");

                    b.Navigation("Parcelas");
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.Importacao", b =>
                {
                    b.Navigation("Arquivos");

                    b.Navigation("Itens");
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.Membro", b =>
                {
                    b.Navigation("Contas");
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.Orcamento", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.PerfilAcesso", b =>
                {
                    b.Navigation("Permissoes");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.Permissao", b =>
                {
                    b.Navigation("Perfis");
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.PermissaoEscopo", b =>
                {
                    b.Navigation("Membros");
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.RateioDespesa", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.Recorrencia", b =>
                {
                    b.Navigation("Ocorrencias");
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.Transferencia", b =>
                {
                    b.Navigation("Transacoes");
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.Usuario", b =>
                {
                    b.Navigation("Sessoes");
                });
#pragma warning restore 612, 618
        }
    }
}
