// <auto-generated />
using System;
using FamilyPlus.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FamilyPlus.Api.Migrations
{
    [DbContext(typeof(FinanceDbContext))]
    [Migration("20260913133245_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("FamilyPlus.Api.Entities.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CategoriaPaiId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaPaiId");

                    b.ToTable("categoria", (string)null);
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.Configuracao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Chave")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Chave")
                        .IsUnique();

                    b.ToTable("configuracao", (string)null);
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.Conta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MembroId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("SaldoInicialCentavos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MembroId");

                    b.ToTable("conta", (string)null);
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.Membro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("membro", (string)null);
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.SessaoLocal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CriadaEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("EncerradaEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiraEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("sessao_local", (string)null);
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.Categoria", b =>
                {
                    b.HasOne("FamilyPlus.Api.Entities.Categoria", "CategoriaPai")
                        .WithMany("Filhas")
                        .HasForeignKey("CategoriaPaiId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CategoriaPai");
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.Conta", b =>
                {
                    b.HasOne("FamilyPlus.Api.Entities.Membro", "Membro")
                        .WithMany("Contas")
                        .HasForeignKey("MembroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Membro");
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.SessaoLocal", b =>
                {
                    b.HasOne("FamilyPlus.Api.Entities.Usuario", "Usuario")
                        .WithMany("Sessoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.Categoria", b =>
                {
                    b.Navigation("Filhas");
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.Membro", b =>
                {
                    b.Navigation("Contas");
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.Usuario", b =>
                {
                    b.Navigation("Sessoes");
                });
#pragma warning restore 612, 618
        }
    }
}
