// <auto-generated />
using System;
using FamilyPlus.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FamilyPlus.Api.Migrations
{
    [DbContext(typeof(FinanceDbContext))]
    [Migration("20260913212631_Sprint3CartoesFaturasParcelas")]
    partial class Sprint3CartoesFaturasParcelas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("FamilyPlus.Api.Entities.Auditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DadosAnteriores")
                        .HasColumnType("TEXT");

                    b.Property<string>("DadosNovos")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("Entidade")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntidadeId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Operacao")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Data");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("Entidade", "EntidadeId");

                    b.ToTable("auditoria", (string)null);
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.Cartao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bandeira")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContaPagamentoPadraoId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<int>("DiaFechamento")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiaVencimento")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LimiteTotalCentavos")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MembroId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("UltimosDigitos")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContaPagamentoPadraoId");

                    b.HasIndex("MembroId");

                    b.ToTable("cartao", (string)null);
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CategoriaPaiId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaPaiId");

                    b.ToTable("categoria", (string)null);
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.CompraCartao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CartaoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DataCompra")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MembroId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacao")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantidadeParcelas")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ValorTotalCentavos")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CartaoId")
                        .HasDatabaseName("IDX_COMPRA_CARTAO");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("DataCompra")
                        .HasDatabaseName("IDX_COMPRA_DATA");

                    b.HasIndex("MembroId");

                    b.ToTable("compra_cartao", (string)null);
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.Configuracao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Chave")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Chave")
                        .IsUnique();

                    b.ToTable("configuracao", (string)null);
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.Conta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MembroId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("SaldoInicialCentavos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MembroId");

                    b.ToTable("conta", (string)null);
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.EstornoCartao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompraCartaoId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FaturaId")
                        .HasColumnType("TEXT");

                    b.Property<long>("ValorCentavos")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompraCartaoId");

                    b.HasIndex("FaturaId");

                    b.ToTable("estorno_cartao", (string)null);
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.Fatura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CartaoId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Competencia")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ContaPagamentoId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DataFechamento")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DataPagamento")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DataVencimento")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ValorTotalCentavos")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CartaoId")
                        .HasDatabaseName("IDX_FATURA_CARTAO");

                    b.HasIndex("Competencia")
                        .HasDatabaseName("IDX_FATURA_COMPETENCIA");

                    b.HasIndex("ContaPagamentoId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IDX_FATURA_STATUS");

                    b.HasIndex("CartaoId", "Competencia")
                        .IsUnique();

                    b.ToTable("fatura", (string)null);
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.Membro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("membro", (string)null);
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.ParcelaCartao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompraCartaoId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DataCompetencia")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FaturaId")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroParcela")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantidadeTotal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ValorCentavos")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompraCartaoId")
                        .HasDatabaseName("IDX_PARCELA_COMPRA");

                    b.HasIndex("DataCompetencia")
                        .HasDatabaseName("IDX_PARCELA_COMPETENCIA");

                    b.HasIndex("FaturaId")
                        .HasDatabaseName("IDX_PARCELA_FATURA");

                    b.ToTable("parcela_cartao", (string)null);
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.SessaoLocal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CriadaEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("EncerradaEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiraEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("sessao_local", (string)null);
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.Transacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CategoriaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContaId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DataCompetencia")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DataMovimentacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MembroId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacao")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Origem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("TransferenciaId")
                        .HasColumnType("TEXT");

                    b.Property<long>("ValorCentavos")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId")
                        .HasDatabaseName("IDX_TRANSACAO_CATEGORIA");

                    b.HasIndex("ContaId")
                        .HasDatabaseName("IDX_TRANSACAO_CONTA");

                    b.HasIndex("DataMovimentacao")
                        .HasDatabaseName("IDX_TRANSACAO_DATA");

                    b.HasIndex("MembroId")
                        .HasDatabaseName("IDX_TRANSACAO_MEMBRO");

                    b.HasIndex("Status")
                        .HasDatabaseName("IDX_TRANSACAO_STATUS");

                    b.HasIndex("TransferenciaId");

                    b.ToTable("transacao", (string)null);
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.Transferencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContaDestinoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContaOrigemId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MembroId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ValorCentavos")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ContaDestinoId");

                    b.HasIndex("ContaOrigemId");

                    b.HasIndex("Data");

                    b.HasIndex("MembroId");

                    b.ToTable("transferencia", (string)null);
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.Auditoria", b =>
                {
                    b.HasOne("FamilyPlus.Api.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.Cartao", b =>
                {
                    b.HasOne("FamilyPlus.Api.Entities.Conta", "ContaPagamentoPadrao")
                        .WithMany()
                        .HasForeignKey("ContaPagamentoPadraoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyPlus.Api.Entities.Membro", "Membro")
                        .WithMany()
                        .HasForeignKey("MembroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ContaPagamentoPadrao");

                    b.Navigation("Membro");
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.Categoria", b =>
                {
                    b.HasOne("FamilyPlus.Api.Entities.Categoria", "CategoriaPai")
                        .WithMany("Filhas")
                        .HasForeignKey("CategoriaPaiId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CategoriaPai");
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.CompraCartao", b =>
                {
                    b.HasOne("FamilyPlus.Api.Entities.Cartao", "Cartao")
                        .WithMany()
                        .HasForeignKey("CartaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyPlus.Api.Entities.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyPlus.Api.Entities.Membro", "Membro")
                        .WithMany()
                        .HasForeignKey("MembroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cartao");

                    b.Navigation("Categoria");

                    b.Navigation("Membro");
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.Conta", b =>
                {
                    b.HasOne("FamilyPlus.Api.Entities.Membro", "Membro")
                        .WithMany("Contas")
                        .HasForeignKey("MembroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Membro");
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.EstornoCartao", b =>
                {
                    b.HasOne("FamilyPlus.Api.Entities.CompraCartao", "CompraCartao")
                        .WithMany("Estornos")
                        .HasForeignKey("CompraCartaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyPlus.Api.Entities.Fatura", "Fatura")
                        .WithMany("Estornos")
                        .HasForeignKey("FaturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CompraCartao");

                    b.Navigation("Fatura");
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.Fatura", b =>
                {
                    b.HasOne("FamilyPlus.Api.Entities.Cartao", "Cartao")
                        .WithMany("Faturas")
                        .HasForeignKey("CartaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyPlus.Api.Entities.Conta", "ContaPagamento")
                        .WithMany()
                        .HasForeignKey("ContaPagamentoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cartao");

                    b.Navigation("ContaPagamento");
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.ParcelaCartao", b =>
                {
                    b.HasOne("FamilyPlus.Api.Entities.CompraCartao", "CompraCartao")
                        .WithMany("Parcelas")
                        .HasForeignKey("CompraCartaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyPlus.Api.Entities.Fatura", "Fatura")
                        .WithMany("Parcelas")
                        .HasForeignKey("FaturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CompraCartao");

                    b.Navigation("Fatura");
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.SessaoLocal", b =>
                {
                    b.HasOne("FamilyPlus.Api.Entities.Usuario", "Usuario")
                        .WithMany("Sessoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.Transacao", b =>
                {
                    b.HasOne("FamilyPlus.Api.Entities.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FamilyPlus.Api.Entities.Conta", "Conta")
                        .WithMany()
                        .HasForeignKey("ContaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyPlus.Api.Entities.Membro", "Membro")
                        .WithMany()
                        .HasForeignKey("MembroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyPlus.Api.Entities.Transferencia", "Transferencia")
                        .WithMany("Transacoes")
                        .HasForeignKey("TransferenciaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Categoria");

                    b.Navigation("Conta");

                    b.Navigation("Membro");

                    b.Navigation("Transferencia");
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.Transferencia", b =>
                {
                    b.HasOne("FamilyPlus.Api.Entities.Conta", null)
                        .WithMany()
                        .HasForeignKey("ContaDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyPlus.Api.Entities.Conta", null)
                        .WithMany()
                        .HasForeignKey("ContaOrigemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyPlus.Api.Entities.Membro", null)
                        .WithMany()
                        .HasForeignKey("MembroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.Cartao", b =>
                {
                    b.Navigation("Faturas");
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.Categoria", b =>
                {
                    b.Navigation("Filhas");
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.CompraCartao", b =>
                {
                    b.Navigation("Estornos");

                    b.Navigation("Parcelas");
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.Fatura", b =>
                {
                    b.Navigation("Estornos");

                    b.Navigation("Parcelas");
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.Membro", b =>
                {
                    b.Navigation("Contas");
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.Transferencia", b =>
                {
                    b.Navigation("Transacoes");
                });

            modelBuilder.Entity("FamilyPlus.Api.Entities.Usuario", b =>
                {
                    b.Navigation("Sessoes");
                });
#pragma warning restore 612, 618
        }
    }
}
